version: '3.0'

services:
  postgres:
    container_name: postgres
    image: postgres:12
    networks:
      - mynet
    env_file:
      - .development.env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
  server:
    container_name: server
    build:
      context: .
    environment:
      - PORT=5000
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 5000:5000
      - 9229:9229
    command: npm run start:dev
    depends_on:
      - postgres
    networks:
      - mynet
    restart: always

volumes:
  pgdata:

networks:
  mynet:
    driver: bridge
